// wisdomData.js - Curated Cultural Wisdom & Bite-Sized Historical Facts about Vietnamese Traditional Costumes

export const CULTURAL_WISDOM_SNIPPETS = [
  {
    id: 'ngu-thuong-buttons',
    categoryVi: 'Đạo Đức & Nhân Sinh',
    categoryEn: 'Ethics & Philosophy',
    icon: 'sparkles',
    titleVi: '5 Chiếc Khuy Áo & Đạo Làm Người "Ngũ Thường"',
    titleEn: '5 Fastening Buttons & The "Five Constant Virtues"',
    factVi: 'Áo ngũ thân truyền thống luôn có đúng 5 chiếc nút cài (nữu), đại diện cho "Ngũ Thường" trong Nho giáo: Nhân (lòng nhân ái), Nghĩa (sự chính trực), Lễ (phép tắc cư xử), Trí (sự sáng suốt), và Tín (giữ trọn lời hứa).',
    factEn: 'The traditional five-panel robe (Áo Ngũ Thân) strictly features 5 fastening buttons, embodying Confucianism\'s "Five Constant Virtues": Benevolence (Nhân), Righteousness (Nghĩa), Propriety (Lễ), Wisdom (Trí), and Trustworthiness (Tín).',
    philosophyVi: 'Mỗi khi cài một chiếc khuy áo, người mặc như tự nhắc nhở bản thân sống trọn vẹn với 5 chuẩn mực đạo đức cốt lõi.',
    philosophyEn: 'Each time a wearer buttons their robe, they mindfully reflect upon the five bedrock moral virtues of noble character.',
    source: 'Khâm Định Đại Nam Hội Điển Sự Lệ',
    eraVi: 'Triều Nguyễn (1802 - 1945)',
    eraEn: 'Nguyen Dynasty (1802 - 1945)'
  },
  {
    id: 'than-con-humility',
    categoryVi: 'Triết Lý May Đo',
    categoryEn: 'Tailoring Philosophy',
    icon: 'user-check',
    titleVi: 'Thân Thứ Năm Ẩn Mình: Bài Học Khiêm Nhường Cốt Lõi',
    titleEn: 'The Hidden Fifth Flap: A Masterclass in Humility',
    factVi: 'Áo Ngũ Thân được ghép từ 5 thân vải. 4 thân bên ngoài tượng trưng cho "Tứ Thân Phụ Mẫu" (cha mẹ ruột và cha mẹ vợ/chồng). Thân thứ 5 (thân con) nằm nép kín đáo phía trong bên phải vạt trước, đại diện cho chính bản thân người mặc.',
    factEn: 'The Áo Ngũ Thân is sewn from five fabric panels. The outer four panels represent the "Four Parents" (one\'s own parents and parents-in-law). The fifth panel (thân con) is tucked discreetly inside, symbolizing the wearer themselves.',
    philosophyVi: 'Bản thân nhỏ bé luôn nép mình vào trong, coi trọng đạo hiếu và sự khiêm tốn trước gia đình và xã hội.',
    philosophyEn: 'The individual quietly tucks within, prioritizing filial piety and modest restraint over individual ostentation.',
    source: 'Vũ Vương Nguyễn Phúc Khoát - Điển Chế Canh Thân 1744',
    eraVi: 'Đàng Trong (Từ năm 1744)',
    eraEn: 'Inner Realm / Dang Trong (From 1744)'
  },
  {
    id: 'duong-trung-phung',
    categoryVi: 'Kỹ Thuật Cắt May',
    categoryEn: 'Tailoring Technique',
    icon: 'shield-check',
    titleVi: 'Đường Trung Phùng: Trục Sống Lưng Của Người Quân Tử',
    titleEn: 'Duong Trung Phung: The Spinal Line of Righteousness',
    factVi: 'Do khổ vải dệt xưa chỉ rộng khoảng 35-40cm, lưng áo ngũ thân bắt buộc phải nối sống ở giữa. Đường may nối thẳng tắp từ chân cổ xuống gấu gọi là "Đường Trung Phùng", luôn ngay ngắn song song với cột sống người mặc.',
    factEn: 'Because ancient handloom silk widths were merely 35-40cm, robes required a vertical central back seam. Known as "Đường Trung Phùng", this dead-straight center line aligns precisely with the wearer\'s spine.',
    philosophyVi: 'Tượng trưng cho sự chính trực, đường hoàng, không xiêu vẹo nghiêng ngả của bậc chính nhân quân tử.',
    philosophyEn: 'Symbolizes upright integrity, uncompromising moral rectitude, and dignity of the noble soul.',
    source: 'Cổ Phục Việt Nam & Điển Chế Dệt May',
    eraVi: 'Thế kỷ XVIII - XX',
    eraEn: '18th - 20th Century'
  },
  {
    id: 'huu-nham-rule',
    categoryVi: 'Quy Chuẩn Cấm Kỵ',
    categoryEn: 'Cultural Guardrail',
    icon: 'alert-triangle',
    titleVi: 'Quy Tắc "Hữu Nhậm": Ranh Giới Giữa Sự Sống & Cõi Vĩnh Hằng',
    titleEn: 'The "Huu Nham" Rule: The Line Between Life and Eternity',
    factVi: 'Trang phục cổ Đại Việt (Áo Giao Lĩnh, Viên Lĩnh) luôn tuân thủ nguyên tắc "Hữu Nhậm": vạt trái vắt chéo lên trên đè lên vạt phải. Ngược lại, cách mặc "Tả Nhậm" (vạt phải đè lên vạt trái) tuyệt đối cấm kỵ vì chỉ dành cho người đã khuất khi khâm liệm.',
    factEn: 'Ancient Dai Viet cross-collar robes strictly adhere to "Hữu Nhậm": the left lapel wraps over the right. Inverting this into "Tả Nhậm" (right over left) is strictly forbidden for the living, as it was historically reserved only for deceased shroud garments.',
    philosophyVi: 'Phân định rõ ranh giới âm dương, tôn vinh nguồn năng lượng sinh sôi và trật tự văn hóa phương Đông.',
    philosophyEn: 'Demarcates cosmic Yin and Yang boundaries, affirming vibrant vital life force and civilizational order.',
    source: 'Đại Việt Sử Ký Toàn Thư & Lễ Ký',
    eraVi: 'Thời Lý - Trần - Lê (1009 - 1789)',
    eraEn: 'Ly - Tran - Le Dynasties (1009 - 1789)'
  },
  {
    id: 'nhat-binh-colors',
    categoryVi: 'Quy Chế Cung Đình',
    categoryEn: 'Imperial Hierarchy',
    icon: 'crown',
    titleVi: 'Màu Sắc Áo Nhật Bình: Trật Tự Quyền Lực Chốn Hoàng Cung',
    titleEn: 'Nhat Binh Color Hierarchy: Royal Status in the Forbidden City',
    factVi: 'Cấp bậc phi tần triều Nguyễn được định danh nghiêm ngặt qua màu áo Nhật Bình: Sắc Vàng Chính Sắc độc quyền cho Hoàng Hậu; màu Đỏ Xích Đào dành cho Công Chúa; màu Tím Thủy Quy dành cho Nhất/Nhị phẩm Phi; và màu Xanh Biển dành cho Tam/Tứ phẩm.',
    factEn: 'Imperial consort ranks in the Nguyen Dynasty were strictly color-coded on Nhat Binh robes: True Imperial Yellow was reserved solely for the Empress; Scarlet Red for Princesses; Royal Violet for 1st/2nd Rank Consorts; and Ocean Blue for 3rd/4th Rank Concubines.',
    philosophyVi: 'Hệ thống màu sắc không chỉ là thẩm mỹ mà là trật tự lễ nghi cung đình bất khả xâm phạm.',
    philosophyEn: 'Color was not merely fashion aesthetic, but an inviolable legal codification of dynastic cosmic order.',
    source: 'Đại Nam Điển Lệ Toát Yếu',
    eraVi: 'Triều Nguyễn (1802 - 1945)',
    eraEn: 'Nguyen Dynasty (1802 - 1945)'
  },
  {
    id: 'tam-son-thuy-ba',
    categoryVi: 'Họa Tiết Biểu Tượng',
    categoryEn: 'Symbolic Motifs',
    icon: 'mountain',
    titleVi: 'Tam Sơn Thủy Ba: Khẳng Định Vĩnh Cửu Về Chủ Quyền Non Sông',
    titleEn: 'Tam Son Thuy Ba: Eternal Assertion of Sacred Homeland',
    factVi: 'Chân vạt áo Nhật Bình, Áo Tấc hoàng tộc luôn có dải thêu "Tam Sơn Thủy Ba": ba ngọn núi thiêng vững chãi nhô lên giữa muôn trùng sóng nước ngũ hành cuộn trào.',
    factEn: 'The bottom hem of imperial Nhat Binh and Ao Tac robes invariably bore the "Tam Sơn Thủy Ba" embroidery: three sacred mountain peaks standing resolute amidst turbulent five-element oceanic waves.',
    philosophyVi: 'Tượng trưng cho giang sơn bờ cõi vĩnh cửu, núi non biển đảo muôn đời bền vững trước phong ba bão táp.',
    philosophyEn: 'Symbolizes the eternal resilience of the sovereign homeland, unshakeable against the relentless tides of time.',
    source: 'Hoa Văn Mỹ Thuật Hoàng Gia Huế',
    eraVi: 'Thế kỷ XIX',
    eraEn: '19th Century'
  },
  {
    id: 'khan-dong-chu-nhan',
    categoryVi: 'Tục Đeo Khăn Vấn',
    categoryEn: 'Headwear Customs',
    icon: 'smile',
    titleVi: 'Khăn Đóng Chữ "Nhân": Đội Lòng Nhân Ái Lên Đầu',
    titleEn: 'The "Nhân" Turban Fold: Wearing Benevolence on One\'s Brow',
    factVi: 'Khăn vấn hay khăn đóng của người Việt khi quấn tạo thành một nếp xếp hình chữ "Nhân" (人) ngay chính giữa trán. Khăn của nam giới thường có 7 hoặc 9 nếp quấn, biểu trưng cho thất khiếu hoặc cửu khiếu.',
    factEn: 'The traditional folded turban (Khăn Đóng) is wrapped so that the front fold forms the character "Nhân" (人 - Humanity/Kindness) directly centered on the forehead. Men\'s turbans traditionally feature 7 or 9 wraps.',
    philosophyVi: 'Nhắc nhở người Việt mỗi sớm mai soi gương đội khăn là đặt chữ "Nhân ái", "Thương người như thể thương thân" lên hàng đầu suy nghĩ.',
    philosophyEn: 'A daily ritual reminding the wearer that benevolence and compassion for fellow beings must crown every thought.',
    source: 'Nếp Cũ - Phong Tục Xưa',
    eraVi: 'Phong tục dân tộc truyền đời',
    eraEn: 'Timeless folk heritage'
  },
  {
    id: 'khau-giau-chi',
    categoryVi: 'Nghệ Thuật Thủ Công',
    categoryEn: 'Artisan Craftsmanship',
    icon: 'scissors',
    titleVi: 'Kỹ Thuật "Khâu Giấu Chỉ" & Nụ Cười Trên Tà Áo',
    titleEn: 'The "Hidden Stitch" Technique & Smiling Robe Hem',
    factVi: 'Các nghệ nhân may cổ phục xưa áp dụng kỹ thuật "khâu giấu chỉ" bậc thầy: toàn bộ đường chỉ luồn bên trong thớ vải, mặt ngoài hoàn toàn không lộ vết kim. Vạt áo được vuốt cong như cánh cung hoặc miệng cười (gọi là "Tà Cánh Cung").',
    factEn: 'Ancient Vietnamese tailors perfected the master "hidden stitch" technique: threads glide entirely inside fabric folds, leaving outer seams invisibly seamless. Hemlines were gently curved like an upward smile ("Tà Cánh Cung").',
    philosophyVi: 'Sự tinh tế không cần phô trương. Đỉnh cao của kỹ nghệ may mặc là giấu đi dấu vết nhân tạo để đạt tới sự tự nhiên hoàn mỹ.',
    philosophyEn: 'Subtle elegance needs no shouting. The pinnacle of craftsmanship conceals the needle to achieve pure natural grace.',
    source: 'Kỹ Nghệ Dệt May Dân Gian Bắc Bộ',
    eraVi: 'Di sản làng nghề truyền thống',
    eraEn: 'Traditional guild heritage'
  },
  {
    id: 'lanh-my-a-diamond',
    categoryVi: 'Chất Liệu Huyền Thoại',
    categoryEn: 'Legendary Textiles',
    icon: 'gem',
    titleVi: 'Lãnh Mỹ A: "Kim Cương Đen" Nhào Nặn Từ Nhựa Quả Mặc Nưa',
    titleEn: 'Lanh My A: The "Black Diamond" Born of Mac Nua Tree Sap',
    factVi: 'Để tạo nên một cây lụa Lãnh Mỹ A đen tuyền bóng như sơn mài, tơ tằm dâu Tân Châu phải trải qua gần 100 lần nhúng nhựa quả Mặc Nưa, phơi nắng sương trên bãi cỏ bạt ngàn và nện búa đá bằng tay suốt 4 đến 6 tháng ròng.',
    factEn: 'To create a single bolt of lacquer-gloss ebony Lãnh Mỹ A silk, Tan Chau mulberry silk undergoes nearly 100 dips in wild Mặc Nưa fruit juices, sun-dew curing on meadows, and rhythmic stone hammer pounding for 4 to 6 months.',
    philosophyVi: 'Một thước vải thấm đẫm mồ hôi, lòng kiên trì và tinh hoa giao hòa giữa trời đất phương Nam.',
    philosophyEn: 'A textile steeped in unyielding human patience, artisan sweat, and cosmic harmony of the Southern Delta.',
    source: 'Di Sản Làng Lụa Tân Châu, An Giang',
    eraVi: 'Thế kỷ XX - Hiện tại',
    eraEn: '20th Century - Present'
  },
  {
    id: 'kieng-bac-circle',
    categoryVi: 'Trang Sức Cổ Phong',
    categoryEn: 'Heritage Jewelry',
    icon: 'circle',
    titleVi: 'Chiếc Kiềng Bạc Tròn: Vòng Tròn Thái Cực & Khí Huyết',
    titleEn: 'The Silver Torc: Taiji Circle & Balanced Vital Energy',
    factVi: 'Kiềng bạc cổ truyền Việt Nam là một vòng tròn trơn khép kín hoặc cài móc đốt tre. Khác với trang sức đính đá phô trương, kiềng bạc hướng tới tính tối giản thuần khiết, đồng thời bạc ta có tính cản gió độc, giữ ấm kinh mạch cổ họng.',
    factEn: 'Traditional Vietnamese solid silver neck torcs (Kiềng) feature a pure circular loop or bamboo-knot clasp. Rather than gaudy gem clusters, it champions serene minimalism, while pure silver shielded the throat against damp drafts.',
    philosophyVi: 'Hình tròn tượng trưng cho trời cao và sự viên mãn, bảo bọc con người trong vòng tay an lành của tổ tiên.',
    philosophyEn: 'The unblemished circle signifies the boundless heavens and wholeness, shielding the wearer in ancestral blessings.',
    source: 'Trang Sức Dân Tộc Học Việt Nam',
    eraVi: 'Cổ đại đến cận đại',
    eraEn: 'Antiquity to Modern Era'
  }
];
